#!bash

# galosh -- amateur radio utilities.
# Copyright (C) 2010 Michael Clarke, M0PRL
# <clarkema -at- clarkema.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file provides bash completion support for Galosh.

_galosh()
{
    local cur prev commands 

    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    commands="log grep export-adif import-adif"

    COMPREPLY=( $(compgen -W "$commands" -- $cur ) )
    return 0
}
complete -F _galosh galosh
