#!bash

# galosh -- amateur radio utilities.
# Copyright (C) 2010, 2011 Michael Clarke, M0PRL
# <mike -at- galosh.org.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This file provides bash completion support for Galosh.

_GALOSH_COMMANDS="browser cluster help lisp-repl log grep export-adif import-adif import-qrz-db qrz recompile-all update"

_galosh_help()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"

    COMPREPLY=( $(compgen -W "$_GALOSH_COMMANDS" -- $cur ) )
    return 0
}

_galosh_import_qrz_db()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"

    _filedir dat
    return 0
}

_galosh_log()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local opts="--complete-missing-entities"

    COMPREPLY=( $(compgen -W "$opts" -- $cur ) )
    return 0
}

_galosh_qrz()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local opts="--offline"

    COMPREPLY=( $(compgen -W "$opts" -- $cur ) )
    return 0
}

_galosh_export_adif()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local opts="--fieldset --list-fieldsets --match"

    COMPREPLY=( $(compgen -W "$opts" -- $cur ) )
    return 0
}

_galosh()
{
    local i c=1 command cur

    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"


    while [ $c -lt $COMP_CWORD ]; do
        i="${COMP_WORDS[c]}"
        case "$i" in
            *) command="$i"; break ;;
        esac
        c=$((++c))
    done

    if [ -z "$command" ]; then
        COMPREPLY=( $(compgen -W "$_GALOSH_COMMANDS" -- $cur ) )
        return 0
    fi

    # Complete options for command
    completion_func="_galosh_${command//-/_}"
    declare -F $completion_func >/dev/null && $completion_func
}
complete -F _galosh galosh
