#! /bin/bash -

mua=$( galosh config tools.mua )

if [ -n "$1" ]; then
    call=$1
else
    until [ -n "$call" ]; do
        read -p "Call: " call
    done
fi

address=$( galosh qrz --raw "$call" | awk -F "\t" '$1 == "email:" { print $2 }' )

if [ -n "$address" ]; then
    ${mua:-echo} $address
else
    echo "No e-mail address found for $call."
fi
