#! /bin/bash -

mua=$( galosh config tools.mua )

if [ -n "$1" ]; then
    call=$1
else
    until [ -n "$call" ]; do
        read -p "Call: " call
    done
fi

address=$( galosh qrz --raw "$call" | awk -F "\t" '$1 == "email:" { print $2 }' ; exit ${PIPESTATUS[0]} )

if [[ $? -eq 0 ]]; then
    if [ -n "$address" ]; then
        if [ -n "$mua" ]; then
            $mua $address
        elif [[ "$OSTYPE" == darwin* ]]; then
            open "mailto:$address"
        else
            echo $address
        fi
    else
        echo "No e-mail address found for $call."
    fi
fi
